-- Example schema for the local Vitess (MySQL 8.4 / Vitess): a document workspace with folders, tags, chats and members.
-- Used only as a realistic development fixture for the local Vitess cluster.

CREATE TABLE `organization` (
  `id` varchar(191) NOT NULL,
  `name` text NOT NULL,
  `slug` varchar(255) DEFAULT NULL,
  `logo` text,
  `created_at` timestamp NOT NULL,
  `metadata` text,
  `hipaa_enabled` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `organization_slug_unique` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `member` (
  `id` varchar(36) NOT NULL,
  `organization_id` varchar(36) NOT NULL,
  `user_id` varchar(36) NOT NULL,
  `role` text NOT NULL DEFAULT (_utf8mb4'member'),
  `created_at` timestamp NOT NULL,
  PRIMARY KEY (`id`),
  KEY `member_organizationId_idx` (`organization_id`),
  KEY `member_userId_idx` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `NewUser` (
  `id` varchar(191) NOT NULL,
  `name` varchar(191) DEFAULT NULL,
  `username` varchar(191) DEFAULT NULL,
  `email` varchar(191) DEFAULT NULL,
  `emailVerified` datetime(3) DEFAULT NULL,
  `image` varchar(191) DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT (now(3)),
  `role` text,
  `email_verified` tinyint(1) NOT NULL DEFAULT '0',
  `banned` tinyint(1) DEFAULT '0',
  `ban_reason` text,
  `ban_expires` timestamp NULL DEFAULT NULL,
  `stripe_customer_id` text,
  `uniqueVisitorId` varchar(191) DEFAULT NULL,
  `is_onboarded` tinyint(1) DEFAULT '0',
  `default_organization_id` text,
  `two_factor_enabled` tinyint(1) DEFAULT '0',
  `apple_account_token` varchar(36) DEFAULT NULL,
  `apple_purchase_organization_id` varchar(191) DEFAULT NULL,
  `apple_original_transaction_id` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `NewUser_username_key` (`username`),
  UNIQUE KEY `NewUser_email_key` (`email`),
  UNIQUE KEY `NewUser_apple_account_token_key` (`apple_account_token`),
  KEY `NewUser_stripeCustomerId_idx` (`stripe_customer_id`(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `Chatbot` (
  `id` varchar(191) NOT NULL,
  `name` text,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `indexUrl` text,
  `documentUrl` text,
  `userId` varchar(191) NOT NULL,
  `deleted` tinyint(1) DEFAULT '0',
  `defaultPrompts` json DEFAULT NULL,
  `isIndexed` tinyint(1) NOT NULL DEFAULT '0',
  `updatedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `isPinecone` tinyint(1) NOT NULL DEFAULT '0',
  `history` varchar(191) DEFAULT NULL,
  `isSupabase` tinyint(1) NOT NULL DEFAULT '0',
  `isHNSWLib` tinyint(1) NOT NULL DEFAULT '0',
  `type` enum('DOCUMENT','GROUP','VIDEO','TEXT','NOTION','NOTE','WEBSITE','WORKSPACE','IMAGE','YOUTUBE','RECORDING','AUDIO','QUIZ','NOTHING','SPREADSHEET','CODE') NOT NULL DEFAULT 'DOCUMENT',
  `groupId` varchar(191) DEFAULT NULL,
  `text` text,
  `isPineconeMetadata` tinyint(1) NOT NULL DEFAULT '0',
  `contents` json DEFAULT NULL,
  `teamId` varchar(191) DEFAULT NULL,
  `url` text,
  `summary` text,
  `isLiveblocks` tinyint(1) NOT NULL DEFAULT '0',
  `isTeamToggled` tinyint(1) NOT NULL DEFAULT '0',
  `isIndex006` tinyint(1) NOT NULL DEFAULT '0',
  `authors` json DEFAULT NULL,
  `isUnstructured` tinyint(1) DEFAULT '0',
  `displayOrder` int DEFAULT NULL,
  `groupCollapsed` tinyint(1) NOT NULL DEFAULT '0',
  `nextId` varchar(191) DEFAULT NULL,
  `originalChatbotId` varchar(191) DEFAULT NULL,
  `knowledgeExtracted` tinyint(1) NOT NULL DEFAULT '0',
  `lastViewedAt` datetime(3) DEFAULT NULL,
  `isInviteToggled` tinyint(1) DEFAULT NULL,
  `organizationId` varchar(191) DEFAULT NULL,
  `isPrivate` tinyint(1) NOT NULL DEFAULT '1',
  `description` text,
  PRIMARY KEY (`id`),
  KEY `Chatbot_userId_idx` (`userId`),
  KEY `Chatbot_groupId_idx` (`groupId`),
  KEY `Chatbot_createdAt_idx` (`createdAt`),
  KEY `Chatbot_organizationId_idx` (`organizationId`),
  KEY `Chatbot_isPrivate_idx` (`isPrivate`),
  KEY `Chatbot_isInviteToggled_idx` (`isInviteToggled`),
  KEY `Chatbot_deleted_idx` (`deleted`),
  KEY `Chatbot_organizationId_isPrivate_userId_idx` (`organizationId`,`isPrivate`,`userId`),
  KEY `Chatbot_org_type_createdAt_idx` (`organizationId`,`type`,`createdAt`),
  KEY `Chatbot_org_type_lastViewedAt_idx` (`organizationId`,`type`,`lastViewedAt`),
  KEY `Chatbot_groupId_org_type_idx` (`groupId`,`organizationId`,`type`),
  KEY `Chatbot_org_type_displayOrder_idx` (`organizationId`,`type`,`displayOrder`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `DocumentMetadata` (
  `chatbotId` varchar(191) NOT NULL,
  `title` varchar(1000) DEFAULT NULL,
  `authors` json DEFAULT NULL,
  `publication` varchar(1000) DEFAULT NULL,
  `volume` varchar(1000) DEFAULT NULL,
  `issue` varchar(1000) DEFAULT NULL,
  `pages` varchar(255) DEFAULT NULL,
  `date` datetime(3) DEFAULT NULL,
  `doi` varchar(1000) DEFAULT NULL,
  `url` varchar(1000) DEFAULT NULL,
  `isbn` varchar(191) DEFAULT NULL,
  `arxivId` varchar(191) DEFAULT NULL,
  `abstract` text,
  `language` varchar(191) DEFAULT NULL,
  `publisher` varchar(1000) DEFAULT NULL,
  `type` varchar(191) DEFAULT NULL,
  `categories` json DEFAULT NULL,
  `primaryCategory` varchar(1000) DEFAULT NULL,
  `subjects` json DEFAULT NULL,
  `description` text,
  `edition` varchar(1000) DEFAULT NULL,
  `series` varchar(1000) DEFAULT NULL,
  `keywords` json DEFAULT NULL,
  `issn` varchar(191) DEFAULT NULL,
  `updated` datetime(3) DEFAULT NULL,
  `citationCount` int NOT NULL DEFAULT '0',
  `openAccess` tinyint(1) NOT NULL DEFAULT '0',
  `openAlexId` varchar(255) DEFAULT NULL,
  `publicationYear` varchar(191) DEFAULT NULL,
  `publicationDate` datetime(3) DEFAULT NULL,
  `citedByUrl` varchar(1000) DEFAULT NULL,
  `relatedWorks` json DEFAULT NULL,
  `referencesCount` int NOT NULL DEFAULT '0',
  `isRetracted` tinyint(1) NOT NULL DEFAULT '0',
  `isParatext` tinyint(1) NOT NULL DEFAULT '0',
  `summary` text,
  `pmid` varchar(191) DEFAULT NULL,
  `metadataFetchAttempted` tinyint(1) NOT NULL DEFAULT '0',
  `metadataFetchVersion` int DEFAULT NULL,
  `fullTextAvailability` enum('AVAILABLE','ABSTRACT_ONLY','CONTENT_UNAVAILABLE') NOT NULL DEFAULT 'CONTENT_UNAVAILABLE',
  `toc` json DEFAULT NULL,
  `pageIndex` json DEFAULT NULL,
  PRIMARY KEY (`chatbotId`),
  KEY `DocumentMetadata_chatbotId_idx` (`chatbotId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `DocumentEntity` (
  `id` varchar(191) NOT NULL,
  `name` varchar(255) NOT NULL,
  `type` varchar(50) NOT NULL,
  `organizationId` varchar(191) NOT NULL,
  `color` varchar(50) DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT (now(3)),
  `createdBy` varchar(191) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `DocumentEntity_organizationId_type_name_key` (`organizationId`,`type`,`name`),
  KEY `DocumentEntity_organizationId_idx` (`organizationId`),
  KEY `DocumentEntity_createdBy_idx` (`createdBy`),
  KEY `DocumentEntity_organizationId_type_name_idx` (`organizationId`,`type`,`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `DocumentEntityLink` (
  `chatbotId` varchar(191) NOT NULL,
  `entityId` varchar(191) NOT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT (now(3)),
  `order` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`chatbotId`,`entityId`),
  KEY `DocumentEntityLink_chatbotId_idx` (`chatbotId`),
  KEY `DocumentEntityLink_entityId_idx` (`entityId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `ChatV3` (
  `id` varchar(191) NOT NULL,
  `title` varchar(500) NOT NULL,
  `userId` varchar(191) NOT NULL,
  `organizationId` varchar(191) DEFAULT NULL,
  `visibility` enum('public','private','workspace') NOT NULL DEFAULT 'private',
  `createdAt` datetime(3) NOT NULL DEFAULT (now(3)),
  `updatedAt` datetime(3) NOT NULL DEFAULT (now(3)),
  `metadata` json DEFAULT NULL,
  `pinnedAt` datetime(3) DEFAULT NULL,
  `titleSetByUser` tinyint(1) NOT NULL DEFAULT '0',
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `ChatV3_userId_idx` (`userId`),
  KEY `ChatV3_organizationId_idx` (`organizationId`),
  KEY `ChatV3_createdAt_idx` (`createdAt`),
  KEY `ChatV3_updatedAt_idx` (`updatedAt`),
  KEY `ChatV3_visibility_idx` (`visibility`),
  KEY `ChatV3_userId_organizationId_updatedAt_idx` (`userId`,`organizationId`,`updatedAt`),
  KEY `ChatV3_userId_organizationId_pinnedAt_idx` (`userId`,`organizationId`,`pinnedAt`),
  KEY `ChatV3_deleted_idx` (`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `MessageV3` (
  `id` varchar(191) NOT NULL,
  `chatId` varchar(191) NOT NULL,
  `role` enum('user','assistant') NOT NULL,
  `parts` json NOT NULL,
  `attachments` json NOT NULL,
  `metadata` json DEFAULT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT (now(3)),
  `parentId` varchar(191) DEFAULT NULL,
  `subAgentToolCallId` varchar(191) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `MessageV3_chatId_idx` (`chatId`),
  KEY `MessageV3_createdAt_idx` (`createdAt`),
  KEY `MessageV3_chatId_createdAt_idx` (`chatId`,`createdAt`),
  KEY `MessageV3_parentId_idx` (`parentId`),
  KEY `MessageV3_subAgentToolCallId_idx` (`subAgentToolCallId`),
  KEY `MessageV3_chatId_subAgentToolCallId_createdAt_idx` (`chatId`,`subAgentToolCallId`,`createdAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `DocumentAnnotation` (
  `id` varchar(191) NOT NULL,
  `pageNumber` int NOT NULL,
  `userDisplayName` varchar(191) NOT NULL,
  `highlights` json NOT NULL,
  `comment` text,
  `color` varchar(191) NOT NULL,
  `text` text NOT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `chatbotId` varchar(191) NOT NULL,
  `userId` varchar(191) NOT NULL,
  `borderColor` varchar(191) NOT NULL,
  `underlines` json DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `DocumentAnnotation_userId_idx` (`userId`),
  KEY `DocumentAnnotation_chatbotId_idx` (`chatbotId`),
  KEY `DocumentAnnotation_id_idx` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `FolderShare` (
  `id` varchar(191) NOT NULL,
  `folderId` varchar(191) NOT NULL,
  `userId` varchar(191) NOT NULL,
  `email` varchar(191) NOT NULL,
  `role` enum('OWNER','FULL_ACCESS','VIEWER') NOT NULL,
  `status` enum('PENDING','ACCEPTED','DECLINED') NOT NULL DEFAULT 'PENDING',
  `invitedBy` varchar(191) NOT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT (now(3)),
  `updatedAt` datetime(3) NOT NULL DEFAULT (now(3)),
  `organizationId` varchar(191) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `FolderShare_folderId_email_key` (`folderId`,`email`),
  KEY `FolderShare_folderId_idx` (`folderId`),
  KEY `FolderShare_userId_idx` (`userId`),
  KEY `FolderShare_email_idx` (`email`),
  KEY `FolderShare_invitedBy_idx` (`invitedBy`),
  KEY `FolderShare_organizationId_idx` (`organizationId`),
  KEY `FolderShare_status_idx` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `SoftDelete` (
  `id` varchar(191) NOT NULL,
  `entityType` enum('CHATBOT','CHAT') NOT NULL,
  `entityId` varchar(191) NOT NULL,
  `trashId` varchar(191) NOT NULL,
  `isRoot` tinyint(1) NOT NULL DEFAULT '1',
  `userId` varchar(191) NOT NULL,
  `organizationId` varchar(191) DEFAULT NULL,
  `deletedById` varchar(191) NOT NULL,
  `deletedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `SoftDelete_entityType_entityId_key` (`entityType`,`entityId`),
  KEY `SoftDelete_trashId_idx` (`trashId`),
  KEY `SoftDelete_deletedAt_idx` (`deletedAt`),
  KEY `SoftDelete_org_isRoot_deletedAt_idx` (`organizationId`,`isRoot`,`deletedAt`),
  KEY `SoftDelete_userId_isRoot_deletedAt_idx` (`userId`,`isRoot`,`deletedAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `invitation` (
  `id` varchar(36) NOT NULL,
  `organization_id` varchar(36) NOT NULL,
  `email` text NOT NULL,
  `role` text,
  `status` text NOT NULL DEFAULT (_utf8mb4'pending'),
  `expires_at` timestamp NOT NULL,
  `inviter_id` varchar(36) NOT NULL,
  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `invitation_organizationId_idx` (`organization_id`),
  KEY `invitation_email_idx` (`email`(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Client bookkeeping for Orbit mutators (see docs/mutations.md).
CREATE TABLE IF NOT EXISTS `orbit_clients` (`client_id` varchar(64) NOT NULL, `partition_key` varchar(191) NOT NULL, `last_mutation_id` bigint NOT NULL DEFAULT 0, `updated_at` datetime(3) NOT NULL, PRIMARY KEY (`client_id`), KEY `orbit_clients_partition` (`partition_key`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
